### ISSUE TITLE
atom需要重新编译twrp吗？

### ISSUE THREAD

**Issue by sumiort** [ymdzq/OFRP-device_xiaomi_bomb#1]
大佬麻烦帮atom制作一下啊，帮帮忙

**Comment by ymdzq** [comment]
理论上内核通用，不需要重新编译，我只有一台手机没有测试，根据酷安回复是有atom用户刷机成功的。你也可以把内核换成atom的内核，把所有写了bomb型号的地方改成atom，重新编译

**Comment by sumiort** [comment]
好的，我试试

**Comment by sumiort** [comment]
刚测试了atom可以刷
