### ISSUE TITLE
我也编译了好多次，都不支持解密data，很郁闷

### ISSUE THREAD

**Issue by xxroot** [ymdzq/OFRP-device_xiaomi_bomb#3]
我也编译了好多次，都不支持解密data，很郁闷。你现在找到解密的方法了吗兄弟？

**Comment by ymdzq** [comment]
解密data需要补充相关文件，光依赖recovery本身是无法单独解密data的，大多数其他能解密data的机型也都是维护者已经加好了相关文件的所以才能解密data，目前是因为搞不定这些文件所以我上传的文件为了能正常开机都没打开橙狐解密功能的开关
按照twrp提供的解密方案这种情况其实还有一种vold解密的思路，官方rec可能也是用的vold解密，在miui系统的init脚本文件里能看到相关命令，但是我不会用，twrp提供的相关文件版本太旧了编译不通过，搞不定
正常开机解密是需要运行teei_daemon、keymaster、gatekeeper三个服务，所以一般给三方rec做解密data需要补充这三个服务的相关文件
现在这个机型的rec是使用的安卓11内核运行在安卓10的rec代码上，所以天生残疾，binder驱动缺失导致servicemanager、hwservicemanager跑不起来，进而就跑不了keymaster、gatekeeper服务，所以就解密不了data，
要解决解密data这个问题，目前我是两个思路，
一个是魔改安卓11内核，把binder驱动搞定，让上述几个服务跑起来，应该就能解密data了（目前我自己是仅仅做到了编译的安卓11内核能开机，剩下搞不定）
另一个就是改用安卓11的rec代码，或许就没有了驱动问题，服务能正常跑起来应该就能解密data了（但是目前这个device我试了在橙狐、twrp、shrp、pbrp这些安卓10的rec上都能使用，但是安卓11的rec全都卡第一屏，而且网上也没有找到已经做好的安卓11的rec开源device作业抄，就用不了安卓11的rec）。

**Comment by xxroot** [comment]
可以直接用最小设备树安卓11的编译，我昨天就是用的这个编译的，能进入TWRP页面，解密相关的我也补了一些文件，但还是不能解密。搞不懂了，我对解密的流程也大概了解，只是具体都需要哪些，还没有弄明白。希望能跟你共同研究解密相关的问题。

**Comment by xxroot** [comment]
另外我有测试机，我可以提供小米MTK任何型号的测试，没有的机器，我可以买。

**Comment by xxroot** [comment]
安卓11需要加入AVB
# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --set_hashtree_disabled_flag
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA2048
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

**Comment by ymdzq** [comment]
好消息是我看了一眼酷安，10x5g的data解密残芯已经搞定了，正好twrp 11你也跑起来了，所以你可以考虑去借鉴一下他的twrp

**Comment by xxroot** [comment]
嗯 ，我也看到了，借签了，编译出来还是不支持解密。尴尬
